In [3]:
import numpy as np

In [11]:
# 1 Rank Array
a = np.array([1, 2, 3, 4])

# 2 rank arrak
b = np.array([[1,2,3], [4,5,6]])

# 3 rank array
c = np.array([[[1, 2, 3], 
			 [4, 5, 6],
			 [7, 8, 9]]])

#3d array
d = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

# passing touple as an array
tup = (1, 2, 3, 4, 5)
e = np.array(tup)

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[1 2 3 4 5]


In [30]:
#accessing array

print(a[2])
print(b[1,:])
print(c[0,:1, 2])
print(d[1,0,:])
print(e)
print(e[-1])

3
[4 5 6]
[3]
[7 8 9]
[1 2 3 4 5]
5


In [33]:
# slicing
# [start : End : Step]
print(a[-3:-1])
print(b[0,:])

[2 3]
[1 2 3]


In [41]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

1
2
3
3
1
