Numpy

In [6]:
import numpy as np

In [7]:
# 1 Rank Array
a = np.array([1, 2, 3, 4])

# 2 rank arrak
b = np.array([[1,2,3], [4,5,6]])

# 3 rank array
c = np.array([[[1, 2, 3], 
			 [4, 5, 6],
			 [7, 8, 9]]])

#3d array
d = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

# passing touple as an array
tup = (1, 2, 3, 4, 5)
e = np.array(tup)

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[1 2 3 4 5]


In [8]:
#accessing array

print(a[2])
print(b[1,:])
print(c[0,:1, 2])
print(d[1,0,:])
print(e)
print(e[-1])

3
[4 5 6]
[3]
[7 8 9]
[1 2 3 4 5]
5


In [9]:
# slicing
# [start : End : Step]
print(a[-3:-1])
print(b[0,:])

[2 3]
[1 2 3]


In [10]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

1
2
3
3
1


In [27]:
print(e.dtype)

a = np.array(a, dtype='S')
print(a)
print(a.dtype)

#a = np.array(a, dtype='i4') # 4 bytes Int
print(a.dtype)

a = np.array(["Apple", "Cherry", "Banana"])
print(a.dtype)

try:
    a = np.array(['a', 2, 3], dtype='i')
    print(a)
except Exception as e:
    print(e)

int64
[b'a' b'2' b'3']
|S21
|S21
<U6
invalid literal for int() with base 10: 'a'


In [36]:
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
print(arr.dtype)

new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

float64
[1 2 3 4 5 6]
int32


In [43]:
# Copy vs View

arr = np.array([1, 2, 3, 4, 5])
cpy_arr = arr.copy()
print(cpy_arr)
cpy_arr[0] = 42
print(arr)
print(cpy_arr, end="\n\n")

# view
view_arr = arr.view()
print(view_arr)
view_arr[1] = 200
print(arr)
print(view_arr, end="\n\n")

print(cpy_arr.base) # None = owns data
print(view_arr.base) # return original array

[1 2 3 4 5]
[1 2 3 4 5]
[42  2  3  4  5]

[1 2 3 4 5]
[  1 200   3   4   5]
[  1 200   3   4   5]

None
[  1 200   3   4   5]


In [70]:
# shape, Reshape

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr.shape)

arr1 = np.array([1, 2, 3, 4, 5], ndmin=4)
print(arr1)
print(arr1.shape, end='\n\n')

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4,3)
print(new_arr.shape)
print(new_arr, end='\n\n')

new_arr = arr.reshape(2, 3, 2)
print(new_arr.shape)
print(new_arr, end='\n\n')

print(new_arr.base) #It creats view


try:
    new_arr = arr.reshape(3,3)
    new_arr = arr.reshape(4, 4)
    print(new_arr)
except Exception as e:
    print(e, end='\n\n')

# we can use -1 that creat array automaticaly  
print(arr.reshape(2, -1))
print(arr.reshape(2, 2, -1))

# note : we can use -1 for any 1 dimension
try:
    print(arr.reshape(-1, -1))
except Exception as e:
    print(e)

(2, 5)
[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
cannot reshape array of size 12 into shape (3,3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
can only specify one unknown dimension


In [186]:
# Iteration

a = np.array([1, 2, 3, 4, 5])

print(a)
for i in a:
    print(i)

b = np.array([[11,12,13,14] , [15,16,17,18]])
print(b)
for i in b:
    for j in i:
        print(j)

c = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(c)
'''
for i in c:
    for j in i:
        for k in j:
            print(k)
'''
# nditerate
print("nditer")
for i in np.nditer(c[:, :, ::2]):
    print(i)

#ndenumerate
print("ndenumerate")
for idx,i in np.ndenumerate(a[:2]):
    print(idx, i)

print('\n\n')

for idx, i in np.ndenumerate(c):
    print(idx, i)

[1 2 3 4 5]
1
2
3
4
5
[[11 12 13 14]
 [15 16 17 18]]
11
12
13
14
15
16
17
18
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
nditer
1
3
4
6
7
9
10
12
ndenumerate
(0,) 1
(1,) 2



(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [126]:
# Join

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# concatenate
print(np.concatenate((a, b), axis=None))
new_arr = np.concatenate((a, b), axis=0)
print(new_arr)
print(new_arr.ndim)

new_arr = np.concatenate((a, b), axis=1)
print(new_arr)
print(new_arr.ndim)
print('\n\n\n')


# stack
print("Stack axis=0, None")
new_arr = np.stack((a, b))
print(new_arr)
new_arr = np.stack((a, b), axis=0) # same as above
print('\n\n')
print("Satck Axis=1")
new_arr = np.stack((a, b), axis=1)
print(new_arr)
print('\n\n')

# vstack
new_arr = np.vstack((a,b))
print("Vertical Stack")
print(new_arr)
print('\n\n')

# hstack
new_arr = np.hstack((a, b))
print("Horizontal Stack")
print(new_arr)
print('\n\n')

# dstack
new_arr = np.dstack((a, b))
print("Depth(Height) stack")
print(new_arr)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2
[[1 2 5 6]
 [3 4 7 8]]
2




Stack axis=0, None
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



Satck Axis=1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]



Vertical Stack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]



Horizontal Stack
[[1 2 5 6]
 [3 4 7 8]]



Depth(Height) stack
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [149]:
# Array Split

arr = np.array([1,2,3,4,5])

newarr = np.array_split(arr, 2)
print(newarr)
print(newarr[0])
print(newarr[1])
print()

# 2-D split
arr = np.array([[1,2,3],[4,5,6], [7,8,9], [10,11,12], [13,14,15]])
new_arr = np.array_split(arr, 3) 
print(new_arr)
print()

# 3-D split
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]]])
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([1, 2, 3]), array([4, 5])]
[1 2 3]
[4 5]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]])]

[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]]), array([[[ 9, 10],
        [11, 12]]])]


In [170]:
# Where

arr = np.arange(10) # [0,1,2,3,4,5,6,7,8,9]
print(np.where(arr == 5))
x = np.where(arr < 5, arr, arr*10 ) #(condition, true, false)
print(x)

y = np.where(arr%2 == 0) # it returns index
print(y)

# search sorted
# it works only in sorted array

arr = np.arange(15)
print(np.searchsorted(arr, 7, side="right"))
print(np.searchsorted(arr, [10,11,12]))

(array([5]),)
[ 0  1  2  3  4 50 60 70 80 90]
(array([0, 2, 4, 6, 8]),)
8
[10 11 12]


In [184]:
# filter

arr = np.array([1,2,3,4,5,6])
filter_arr = [True, False, False, True, False, True]
new_arr = arr[filter_arr]
print(new_arr)
print()

arr = np.array([1,2,3,4,5])
filter_arr = arr%2 == 0
print(arr[filter_arr])
filter_arr = arr > 2
print(arr[filter_arr])

[1 4 6]

[2 4]
[3 4 5]


In [176]:
# sort

arr = np.array([1,0,52,33,45,21,65,23])
sorted_arr = np.sort(arr)
print(sorted_arr)

# 2-D array sort
arr = np.array([[2,0,6,5,9],[6,0,8,9,1]])
sorted_arr = np.sort(arr)
print(sorted_arr)

arr = np.array([False, True, True, False, False])
print(np.sort(arr))

[ 0  1 21 23 33 45 52 65]
[[0 2 5 6 9]
 [0 1 6 8 9]]
[False False False  True  True]
