Universal functions

In [1]:
import numpy as np

In [2]:
print(type(np.concatenate))
print(type(np.add))
print(type(np.sum))

<class 'numpy._ArrayFunctionDispatcher'>
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [3]:
# zip() ufunction
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = []

for i,j in zip(list1, list2):
    print(i,j)
    list3.append(i+j)
print(list3)

list4 = np.add(list1 , list2)
print(list4)

1 6
2 7
3 8
4 9
5 10
[7, 9, 11, 13, 15]
[ 7  9 11 13 15]


In [4]:
def myfunc(x, y):
    return x+y
    
myfunc = np.frompyfunc(myfunc, 2, 1)

list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = myfunc(list1, list2)
print(list3)

def multiply(x, y, z):
    return x*y*z
    
multiply = np.frompyfunc(multiply, 3, 1)
print(multiply(list1, list2, list3))

[6 8 10 12]
[30 96 210 384]


In [5]:
# arithmetic functions

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(np.add(list1, list2))
print(np.subtract(list2, list1))
print(np.multiply(list1, list2))
print(np.divide(list2, list1))
print(np.pow(list2, list1))
print(np.mod(list2, list1))
print(np.remainder(list2, list1))
print(np.divmod(list2, list1)) # 1:quotient 2:remainder
print(np.abs([-1,2,-3,-4,-5]))


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[     6     49    512   6561 100000]
[0 1 2 1 0]
[0 1 2 1 0]
(array([6, 3, 2, 2, 2]), array([0, 1, 2, 1, 0]))
[1 2 3 4 5]


In [6]:
# rounding decimals

list = np.array([-5.166, -3.678, 2.666, 3.133, 6.999, 7.515])

print(np.trunc(list))
print(np.fix(list))
print()
print(np.around(list))
print(np.floor(list))
print(np.ceil(list))

[-5. -3.  2.  3.  6.  7.]
[-5. -3.  2.  3.  6.  7.]

[-5. -4.  3.  3.  7.  8.]
[-6. -4.  2.  3.  6.  7.]
[-5. -3.  3.  4.  7.  8.]


In [7]:
# log 
arr = np.arange(1,11)

print("Base 2")
print(np.log2(arr), end="\n\n")
print("Base 10")
print(np.log10(arr), end='\n\n')
print("Base e or no Base")
print(np.log(arr), end='\n\n')

from math import log
logfunc = np.frompyfunc(log, 2, 1)
print(logfunc(100, 2))

Base 2
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]

Base 10
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]

Base e or no Base
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]

6.643856189774725
