Universal functions

10/6/25

In [1]:
import numpy as np

In [2]:
print(type(np.concatenate))
print(type(np.add))
print(type(np.sum))

<class 'numpy._ArrayFunctionDispatcher'>
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [3]:
# zip() ufunction
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = []

for i,j in zip(list1, list2):
    print(i,j)
    list3.append(i+j)
print(list3)

list4 = np.add(list1 , list2)
print(list4)

1 6
2 7
3 8
4 9
5 10
[7, 9, 11, 13, 15]
[ 7  9 11 13 15]


In [4]:
def myfunc(x, y):
    return x+y
    
myfunc = np.frompyfunc(myfunc, 2, 1)

list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = myfunc(list1, list2)
print(list3)

def multiply(x, y, z):
    return x*y*z
    
multiply = np.frompyfunc(multiply, 3, 1)
print(multiply(list1, list2, list3))

[6 8 10 12]
[30 96 210 384]


In [5]:
# arithmetic functions

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(np.add(list1, list2))
print(np.subtract(list2, list1))
print(np.multiply(list1, list2))
print(np.divide(list2, list1))
print(np.pow(list2, list1))
print(np.mod(list2, list1))
print(np.remainder(list2, list1))
print(np.divmod(list2, list1)) # 1:quotient 2:remainder
print(np.abs([-1,2,-3,-4,-5]))


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[     6     49    512   6561 100000]
[0 1 2 1 0]
[0 1 2 1 0]
(array([6, 3, 2, 2, 2]), array([0, 1, 2, 1, 0]))
[1 2 3 4 5]


In [6]:
# rounding decimals

list = np.array([-5.166, -3.678, 2.666, 3.133, 6.999, 7.515])

print(np.trunc(list))
print(np.fix(list))
print()
print(np.around(list))
print(np.floor(list))
print(np.ceil(list))

[-5. -3.  2.  3.  6.  7.]
[-5. -3.  2.  3.  6.  7.]

[-5. -4.  3.  3.  7.  8.]
[-6. -4.  2.  3.  6.  7.]
[-5. -3.  3.  4.  7.  8.]


In [7]:
# log 
arr = np.arange(1,11)

print("Base 2")
print(np.log2(arr), end="\n\n")
print("Base 10")
print(np.log10(arr), end='\n\n')
print("Base e or no Base")
print(np.log(arr), end='\n\n')

from math import log
logfunc = np.frompyfunc(log, 2, 1)
print(logfunc(100, 2))

Base 2
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]

Base 10
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]

Base e or no Base
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]

6.643856189774725


11/6/25

In [8]:
# difference add & sum
list1 = [1,2,3]
list2 = [1,2,3]
print(np.add(list1, list2)) # only 2 array
print(np.sum([list1, list2])) # multiple array
print(np.sum([list1, list2], axis=0))
print(np.sum([list1, list2], axis=1))

print(np.cumsum(list1))

[2 4 6]
12
[2 4 6]
[6 6]
[1 3 6]


In [9]:
# product, cumulative product

list1 = [1,2,3]
list2 = [4,5,6]

print(np.prod(list1))
print(np.prod([list1, list2]))
print(np.prod([list1, list2], axis=1))
print(np.cumprod(list1))
print(np.cumprod([list1, list2]))

6
720
[  6 120]
[1 2 6]
[  1   2   6  24 120 720]


In [10]:
# difference
list1 = [5, 10, 25, 5]

print(np.diff(list1)) # [10-5, 25-10, 5-25]
print(np.diff(list1, n=2)) # [10-5, 25-10, 5-25] = [5, 15, -20] = [15-5, -20-15] = [10, -35] (n=2)

[  5  15 -20]
[ 10 -35]


In [11]:
# LCM Lowest common multiplier

num1 = 4
num2 = 6

print(np.lcm(num1, num2)) # 4*3=12, 6*2=12
print(np.lcm.reduce([1,2,3,4,5])) # for multiple values reduce()

# GCD Greatest common divisor

num1 = 6
num2 = 9

print(np.gcd(num1, num2))
print(np.gcd.reduce([4, 12, 20, 32, 36]))

12
60
3
4


In [12]:
# trigonometric function
# sin, cos, tan
arr = np.array([np.pi/1, np.pi/2, np.pi/3, np.pi/4])
print(np.sin(np.pi/2))
print("Sin")
print(np.sin(arr))
print("Cos")
print(np.cos(arr))
print("Tan")
print(np.tan(arr))

print("sinh")
print(np.sinh(arr))
print("cosh")
print(np.cosh(arr))
print("tanh")
print(np.tanh(arr))

1.0
Sin
[1.22464680e-16 1.00000000e+00 8.66025404e-01 7.07106781e-01]
Cos
[-1.00000000e+00  6.12323400e-17  5.00000000e-01  7.07106781e-01]
Tan
[-1.22464680e-16  1.63312394e+16  1.73205081e+00  1.00000000e+00]
sinh
[11.54873936  2.3012989   1.24936705  0.86867096]
cosh
[11.59195328  2.50917848  1.60028686  1.32460909]
tanh
[0.99627208 0.91715234 0.78071444 0.6557942 ]


In [13]:
# degree, radian

arr = np.array([45, 90, 180, 270, 360])
print("Degree to radian")
print(np.deg2rad(arr))

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
print("Radian to degree")
print(np.rad2deg(arr))
print()

# finding angles
arr = np.array([-1, 0.1, 1.0])
print("sin")
print(np.arcsin(arr))
print("cos")
print(np.arccos(arr))
print("tan")
print(np.arctan(arr))

arr = np.array([0.1, 0.2, 0.5])
print("sinh")
print(np.arcsinh(arr))
print("cosh")
print(np.arccosh(1.0))
print("tanh")
print(np.arctanh(arr))

#hypotenues
base = 3
prep = 4
print(np.hypot(base, prep))


Degree to radian
[0.78539816 1.57079633 3.14159265 4.71238898 6.28318531]
Radian to degree
[ 90. 180. 270. 360.]

sin
[-1.57079633  0.10016742  1.57079633]
cos
[3.14159265 1.47062891 0.        ]
tan
[-0.78539816  0.09966865  0.78539816]
sinh
[0.09983408 0.19869011 0.48121183]
cosh
0.0
tanh
[0.10033535 0.20273255 0.54930614]
5.0


In [15]:
# sets

#unique
print("unique")
arr = np.array([1,1,1,2,3,4,5,5,5,6])
print(np.unique(arr))

#union
print("union")
arr1 = np.array([1,2,3,3,4,5,6])
arr2 = np.array([3,4,5,6,7,8])
print(np.union1d(arr1, arr2)) #union1d

#intersection
print("intersection")
print(np.intersect1d(arr1, arr2)) #intersect1d
print(np.intersect1d(arr1, arr2, assume_unique=True))

#difference
arr1 = np.array([1,1,2,3,4])
arr2 = np.array([3,4,5,6])
print("differenbce")
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2, assume_unique=True))

# symmetric difference 
# xor :  values that are NOT present in BOTH sets 
# same value = false, diff value = true
arr1 = np.array([1,1,2,3,4])
arr2 = np.array([3,4,5,6])
print("symmetric diff")
print(np.setxor1d(arr1, arr2))
print(np.setxor1d(arr1, arr2, assume_unique=True))

unique
[1 2 3 4 5 6]
union
[1 2 3 4 5 6 7 8]
intersection
[3 4 5 6]
[3 3 4 5 6]
differenbce
[1 2]
[1 1 2]
symmetric diff
[1 2 5 6]
[2 5 6]
