In [1]:
import torch

In [2]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 2050'

In [3]:
x = [1, 2, 3] 
tensor = torch.tensor([1, 2, 3])
print(tensor)

tensor([1, 2, 3])


In [4]:
torch.ones_like(tensor)

tensor([1, 1, 1])

In [5]:
torch.rand_like(tensor, dtype=torch.float32)

tensor([0.9135, 0.0822, 0.1966])

In [6]:
shape = (2, 3, )

print(torch.rand(shape))
print(torch.ones(shape))
print(torch.zeros(shape))

tensor([[0.6588, 0.7464, 0.3788],
        [0.1889, 0.9428, 0.1988]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
print(tensor.device)

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())


# By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator 
# using .to method (after checking for accelerator availability). Keep in mind that copying large tensors 
# across devices can be expensive in terms of time and memory!

cpu


In [8]:
tensor = torch.ones(4, 4)

print(f"Fiest row : {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

Fiest row : tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [9]:
tensor[:,1] = 0
t1 = torch.cat([tensor, tensor, tensor], dim=1) # concatenation
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)

print(f" {z1} \n {z2} \n {z3}")

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[0.9335, 0.1458, 0.6221, 0.4449],
        [0.0618, 0.8260, 0.4493, 0.9524],
        [0.8966, 0.3471, 0.5967, 0.0342],
        [0.4055, 0.8666, 0.2993, 0.1032]])


In [11]:
print(f"{tensor} \n")
tensor.add_(5) # _ suffix indicates in-place operation
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
# numpy and tensor share the same memory location

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
