In [1]:
import tensorflow as tf

Constants

In [2]:
x = tf.constant([[1., 2.], [3., 4.]])
print(x)
print(x.dtype)
print(x.shape)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<dtype: 'float32'>
(2, 2)


.numpy() to print value of tensor

In [3]:
print(x.numpy())

[[1. 2.]
 [3. 4.]]


In [4]:
x + x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [5]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 11.],
       [11., 25.]], dtype=float32)>

Activation function Calculation with constant

In [6]:
tf.nn.tanh(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7615942 , 0.9640276 ],
       [0.9950547 , 0.99932927]], dtype=float32)>

In [7]:
tf.nn.softmax(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.26894143, 0.73105854],
       [0.26894143, 0.73105854]], dtype=float32)>

In [8]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

Math functions

In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [10]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c).numpy())


# Find the index of the largest value
print(tf.math.argmax(c).numpy()) # 1 row and 0 column = 10.0

10.0
[1 0]


Functions

In [11]:
x = tf.Variable(2.0)

def f(x):
  y = x**2
  return y

f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [13]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

x = tf.constant([1, 2, 3])
print(my_func(x))

x = tf.constant([10.0, 9.1, 8.2], dtype=tf.float32)
print(my_func(x))

Tracing.

tf.Tensor(6, shape=(), dtype=int32)
Tracing.

tf.Tensor(27.3, shape=(), dtype=float32)


In [18]:
@tf.function
def compute(x, y):
    return x * y + 5

z = compute(tf.constant(3.0), tf.constant(2.0))
print(z)
print(z.numpy())


tf.Tensor(11.0, shape=(), dtype=float32)
11.0


Manipulating Shapes

In [19]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [21]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


Ragged tensor

In [24]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

  
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


String 

In [25]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)
print(tensor_of_strings.shape)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)
(3,)


In [28]:
emoji = tf.constant("🥳👍")
print(emoji)

tf.Tensor(b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d', shape=(), dtype=string)


In [29]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


sparse tensor

In [30]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


Calculating gradient

In [31]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y = x**2

In [32]:
# dy = 2x * dx
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

np.float32(6.0)