In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sys
pd.options.mode.copy_on_write = True

In [2]:
#original_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df = pd.read_csv('titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
# select useful column
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [4]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB


In [5]:
# filling null age cell

df['Age'] = df['Age'].fillna(df['Age'].median())
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  28.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [6]:
# converting sex into number
values =  pd.get_dummies(df['Sex'], drop_first=True, dtype='int')
df['Sex'] = values
df.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [7]:
df[['Pclass', 'Age', 'Fare']] = (df[['Pclass', 'Age', 'Fare']] - df[['Pclass', 'Age', 'Fare']].mean()) / df[['Pclass', 'Age', 'Fare']].std()
df

Survived    Pclass  Sex       Age      Fare
0           0  0.826913    1 -0.565419 -0.502163
1           1 -1.565228    0  0.663488  0.786404
2           1  0.826913    0 -0.258192 -0.488580
3           1 -1.565228    0  0.433068  0.420494
4           0  0.826913    1  0.433068 -0.486064
..        ...       ...  ...       ...       ...
886         0 -0.369158    1 -0.181385 -0.386454
887         1 -1.565228    0 -0.795839 -0.044356
888         0  0.826913    0 -0.104579 -0.176164
889         1 -1.565228    1 -0.258192 -0.044356
890         0  0.826913    1  0.202648 -0.492101

[891 rows x 5 columns]

In [8]:
X = df[['Pclass', 'Age', 'Fare']].values
Y = df['Survived'].values.reshape(-1, 1)

print(X)
print(Y)

[[ 0.82691282 -0.5654189  -0.50216314]
 [-1.56522783  0.66348839  0.78640362]
 [ 0.82691282 -0.25819208 -0.48857985]
 ...
 [ 0.82691282 -0.10457867 -0.1761643 ]
 [-1.56522783 -0.25819208 -0.04435613]
 [ 0.82691282  0.20264816 -0.49210144]]
[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]


In [9]:
X = np.hstack([np.ones((X.shape[0], 1)), X])
X

array([[ 1.        ,  0.82691282, -0.5654189 , -0.50216314],
       [ 1.        , -1.56522783,  0.66348839,  0.78640362],
       [ 1.        ,  0.82691282, -0.25819208, -0.48857985],
       ...,
       [ 1.        ,  0.82691282, -0.10457867, -0.1761643 ],
       [ 1.        , -1.56522783, -0.25819208, -0.04435613],
       [ 1.        ,  0.82691282,  0.20264816, -0.49210144]],
      shape=(891, 4))

In [10]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.hstack([np.ones((x.shape[0],1)), x])  # np.ones((x.shape[0] (3 row), (1 Column)))
y

array([[1., 1., 2., 3.],
       [1., 4., 5., 6.],
       [1., 7., 8., 9.]])

In [27]:
df._is_view

False