In [2]:
import numpy as np

In [18]:
# empty
np.empty((2,2), dtype='int', device='cpu') # uninitialized device = API, cpu, divice on which an array is created

array([[            0, 3174112931456],
       [3174112933616, 3174112930976]])

In [22]:
# empty like
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.empty_like(a, dtype='float')

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [27]:
# eye
a = np.array([[1,0,0,],
              [0,1,0],
              [0,0,1]])
np.eye(N=4, M=4, dtype='float')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.eye(N=4, k=1, dtype='int')

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [34]:
# identity
np.identity(3, dtype='int')  # N*N array with only 1 in diagonal place

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
# Zero Like
a = ([[1,2,3,4], [4,5,6,7]])
np.zeros_like(a, order='F')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((5,5), dtype='str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [46]:
# one like
a = ([[1,2], [3,4], [5,6]])
np.ones_like(a, order='K') #order = C : Row major, F : column major, F : as close as provided layout

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
np.full(5, 'Hello')

array(['Hello', 'Hello', 'Hello', 'Hello', 'Hello'], dtype='<U5')

In [42]:
a = ([[1, 2, 3], [4,5,6]])
np.full_like(a, fill_value=1)

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
# asarray

a = np.array([1,2])

b = np.asarray(a)
print(b)
b is a

[1 2]


True

In [63]:
np.shares_memory(a, b)

True

In [64]:
c = np.asarray(a, copy=True)
print(c)
c is a

[1 2]


False

In [65]:
np.shares_memory(a, c)

False

In [70]:
# as any array

a = [1,2]

b = np.asanyarray(a)
b 

array([1, 2])

In [73]:
# matrix
a = [[1,2,3], [4,5,6]]

np.matrix(a) 

matrix([[1, 2, 3],
        [4, 5, 6]])

In [75]:
# as matrix
np.asmatrix(a, dtype='float')

matrix([[1., 2., 3.],
        [4., 5., 6.]])